#define SLCSS		getslang(1)
#define SLBODYTAG       getslang(5)
#define SLHEADER        getslang(10)
#define SLFOOTER        getslang(11)

#define ROOTTITLE	getslang(100)
#define SLTOP		getslang(105)

#define SLTOTAL		getslang(110)
#define SLDAILY		getslang(111)
#define SLWEEKLY	      getslang(112)
#define SLMONTHLY	      getslang(113)
#define SLLTOTAL        getslang(114)
#define SLLTODAY        getslang(115)
#define SLLWEEKLY       getslang(116)
#define SLLMONTHLY      getslang(117)
#define SLUSERS		getslang(118)
#define SLONCHAN        getslang(119)
#define SLMISCSTATS	getslang(120)

#define SLINDEXTITEL	getslang(130)

#define SLTTOPTITLE	getslang(200)
#define SLDTOPTITLE	getslang(201)
#define SLWTOPTITLE	getslang(202)
#define SLMTOPTITLE	getslang(203)
#define SLTTOPHEAD	getslang(210)
#define SLDTOPHEAD	getslang(211)
#define SLWTOPHEAD	getslang(212)
#define SLMTOPHEAD	getslang(213)
#define SLORDEREDBY	getslang(214)
#define SLPEAK		getslang(215)
#define SLTNR           getslang(216)
#define SLTOTALUSERS	getslang(217)
#define SLGSTARTED	getslang(218)
#define SLGRAPHS	      getslang(220)
#define SLOTHERCHANS	getslang(221)

#define SLYEAR		getdur(0)
#define SLYEARS         getdur(1)
#define SLWEEK          getdur(2)
#define SLWEEKS         getdur(3)
#define SLDAY           getdur(4)
#define SLDAYS          getdur(5)
#define SLHOUR          getdur(6)
#define SLHOURS         getdur(7)
#define SLMINUTE        getdur(8)
#define SLMINUTES       getdur(9)
#define SLSECOND	      getslang(260)
#define SLSECONDS	      getslang(261)

#define SLGRTTITLE	getslang(300)
#define SLGRDTITLE	getslang(301)
#define SLGRWTITLE	getslang(302)
#define SLGRMTITLE	getslang(303)
#define SLGRTHEAD	      getslang(310)
#define SLGRDHEAD	      getslang(311)
#define SLGRWHEAD	      getslang(312)
#define SLGRMHEAD	      getslang(313)
#define SLGRORDEREDBY	getslang(320)
#define SLGRTOTAL	      getslang(321)
#define SLGROTHERS	getslang(322)
#define SLGRTABLE	      getslang(323)

#define SLUSERSTITLE	getslang(400)
#define SLUSERSONCHANTITLE      getslang(410)
#define SLNOWONCHAN	getslang(420)
#define SLIDLETIME	getslang(430)
#define SLNETSPLITTED   getslang(435)
#define SLITSME         getslang(436)

#define SLEMAIL		getslang(450)
#define SLHOMEPAGE	getslang(451)

#define SLUSERTITLE	getslang(500)
#define SLUSERHEAD	getslang(501)
#define SLPLACE getslang(502)
#define SLRANDQUOTE	getslang(510)
#define SLUWORDSTATS	getslang(520)
#define SLOTHERUSERS	getslang(530)

#define SLMISCTITLE	getslang(600)
#define SLMISCHEAD	getslang(610)
#define SLMAUSERS       getslang(620)
#define SLMTOPICS	      getslang(630)
#define SLMTOPICBY     	getslang(631)
#define SLMURLS         getslang(640)
#define SLMURLBY        getslang(641)
#define SLMMOSTUSED	getslang(650)
#define SLMISPS		getslang(651)
#define SLMTLDS		getslang(652)
#define SLMKICKS        getslang(660)
#define SLMCWORDSTATS	getslang(670)
#define SLMMOSTUSEDWORDS	getslang(671)

#define SLSTATICTITLE   getslang(900)
#define SLSTATICBODY    getslang(901)

#define SLNOSUCHTYPE    getslang(1000)
#define SLTOPWORD       getslang(1005)
#define SLNOSTATSABOUTYOU     getslang(1010)
#define SLNOSTATSABOUTSOMEONE getslang(1011)
#define SLNOWORDSTATS         getslang(1016)
#define SLUSERSMOSTUSEDWORDS  getslang(1017)
#define SLCHANSMOSTUSEDWORDS  getslang(1018)
#define SLDONTRECOGNIZE	getslang(1020)
#define SLEMAILUSAGE	getslang(1021)
#define SLSETEMAIL	getslang(1022)
#define SLHPUSAGE	getslang(1023)
#define SLSETHOMEPAGE	getslang(1024)
